[package]
name = "emotech-grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.8.1"
prost = "0.11.0"

[dependencies.tokio]
version = "1.21.0"
features = ["full"]

[dependencies.clap]
version = "3.2.20"
features = ["derive"]

[build-dependencies]
tonic-build = "0.8.0"
